#!/bin/sh -efu

. "${0%/*}/tests-sh-functions"

tc_init

mkdir -p -- "$rootdir"/bin
touch "$rootdir"/bin/aaa
chmod 755 "$rootdir"/bin/aaa

tc_state 1

subst < "$datadir/osec-$i.report" > "$tmpdir/expect-$i"
osec | subst > "$tmpdir/output-$i"
diff -u "$tmpdir/expect-$i" "$tmpdir/output-$i"

tc_state 2

subst < "$datadir/osec-$i.report" > "$tmpdir/expect-$i"
osec -t sha512 | subst > "$tmpdir/output-$i"
diff -u "$tmpdir/expect-$i" "$tmpdir/output-$i"

echo 123 > "$rootdir"/bin/aaa

tc_state 3

subst < "$datadir/osec-$i.report" > "$tmpdir/expect-$i"
osec -t sha512 | subst > "$tmpdir/output-$i"
diff -u "$tmpdir/expect-$i" "$tmpdir/output-$i"

echo 456 > "$rootdir"/bin/aaa

tc_state 4

subst < "$datadir/osec-$i.report" > "$tmpdir/expect-$i"
osec | subst > "$tmpdir/output-$i"
diff -u "$tmpdir/expect-$i" "$tmpdir/output-$i"

echo 789 > "$rootdir"/bin/aaa

tc_state 5

subst < "$datadir/osec-$i.report" > "$tmpdir/expect-$i"
osec -t sha1 | subst > "$tmpdir/output-$i"
diff -u "$tmpdir/expect-$i" "$tmpdir/output-$i"

tc_state 6

subst < "$datadir/osec-$i.report" > "$tmpdir/expect-$i"
osec -t sha512 | subst > "$tmpdir/output-$i"
diff -u "$tmpdir/expect-$i" "$tmpdir/output-$i"
