#!/bin/sh
# osec_mailer
#
# This file is part of Osec (lightweight integrity checker)
# Copyright (c) 2002-2007 by Stanislav Ievlev
# Copyright (c) 2009 by Alexey Gladkov
#
# This file is covered by the GNU General Public License,
# which should be included with osec as the file COPYING.
#

PROG="${0##*/}"

. /etc/osec/pipe.conf

TEMPFILE=
exit_handler()
{
	local rc=$?
	trap - EXIT
	[ -z "$TEMPFILE" ] ||
		rm -rf -- "$TEMPFILE"
	exit $rc
}

trap exit_handler HUP PIPE INT QUIT TERM EXIT
TEMPFILE="$(mktemp -t "$PROG.XXXXXX")"

cat >"$TEMPFILE"

ADDED=0 REMOVED=0 CHANGED=0
while read l; do
	case "$l" in
		'No changes')
			[ -z "${IGNORE_NO_CHANGES-}" ] ||
				exit 0
			;;
		'New files added to control:')	t='ADDED'	;;
		'Changed controlled files:')	t='CHANGED'	;;
		'Removed from control:')	t='REMOVED'	;;
		'- /'*) [ -z "${t-}" ] || eval "$t=\$((\$t+1))"	;;
	esac
done < "$TEMPFILE"

STAT="chg=$CHANGED,add=$ADDED,del=$REMOVED"

cat "$TEMPFILE" |
	eval $MAIL_PIPE
