#!/bin/sh
# osec_mailer
#
# This file is part of Osec (lightweight integrity checker)
# Copyright (c) 2002-2007 by Stanislav Ievlev
#
# This file is covered by the GNU General Public License,
# which should be included with osec as the file COPYING.
#

PROG="${0##*/}"

. /etc/osec/pipe.conf

TEMPFILE=
exit_handler()
{
	local rc=$?
	trap - EXIT
	rm -rf -- "$TEMPFILE"
	exit $rc
}

trap exit_handler HUP PIPE INT QUIT TERM EXIT

TEMPFILE="$(mktemp -t "$PROG.avail.XXXXXX")"

cat >"$TEMPFILE"

grep -qs '^No changes' "$TEMPFILE" ||
	(cat "$TEMPFILE" |eval $MAIL_PIPE)
