#!/usr/bin/perl -w

use strict;

use RPM::Database;

my $rpm = new RPM::Database;

while(<STDIN>)
{
    if ( /^\s+-\s+(.*)/ )
    {
	my  $name= join(',', map {$_->{name}} $rpm->find_by_file($1));
	$name eq "" and $name="unknown";
	print "\t- [$name] $1\n";
    }
    else
    {
	print;
    }
}
